[package]
name = "branches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "branches"
path = "src/branches.rs"

[dependencies]
